name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
   name: Build container
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        username: 'filsserge@gmail.com'
        password: '@ZoeElsa22'
        repository: msusdev/webnext
        tags: latest, ${{ github.run_number }}
    - name: Publish to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/webnext
        tags: latest, ${{ github.run_number }}
